"""maybe final migration#34234

Revision ID: be6dee87882a
Revises: b02eba29e386
Create Date: 2021-06-22 13:20:59.945707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6dee87882a'
down_revision = 'b02eba29e386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_date')
    # ### end Alembic commands ###
