"""maybe final migration#toomuch

Revision ID: b807eafc0a2f
Revises: be6dee87882a
Create Date: 2021-06-22 13:22:35.204646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b807eafc0a2f'
down_revision = 'be6dee87882a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_date')
    # ### end Alembic commands ###
